on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
name: PR checks
jobs:
  go-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.0-beta2
        stable: false
    - name: Checkout code
      uses: actions/checkout@v2
    - name: gofmt
      uses: gametimesf/github-actions/go/fmt@v0.5.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Test
      run: go test -cover -race ./...
