on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
name: PR checks
jobs:
  go-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: gofmt
        run: |
          RESULT=$(gofmt -l -d -e .)
          LINECOUNT=$(echo "$RESULT" | wc -l)
          if [ $LINECOUNT -eq 1 ]; then 
            exit 0
          fi
          for LINE in $RESULT
            echo "$LINE"
            echo
          exit 1
          fi
      - name: Test
        run: go test -cover -race ./...
